module Pluginator

  # base error for all Pluginator errors
  class PluginatorError < RuntimeError
  private
    def list_to_s(list)
      list.map{|e| "'#{e}'" }.join(", ")
    end
  end

  # raised when plugin can not be found, generated by `*!` methods
  class MissingPlugin < PluginatorError
    # @param type [String] type of the loaded plugin
    # @param name [String] name of the loaded plugin
    # @param list [Array]  list of available plugins
    def initialize(type, name, list)
      super("Can not find plugin '#{name}' in #{list_to_s(list)} for type '#{type}'.")
    end
  end

  # raised when type can not be found, generated by `*!` methods
  class MissingType < PluginatorError
    # @param type [String] type of the loaded plugin
    # @param list [Array]  list of available types
    def initialize(type, list)
      super("Can not find type '#{type}' in #{list_to_s(list)}.")
    end
  end
end
